---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990
    namers:
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.out
      host: localhost
      port: 8001
      transformers:
      - kind: io.l5d.k8s.daemonset
        namespace: default
        port: incoming
        service: l5d
        hostNetwork: true
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.in
      host: localhost
      port: 8001
    - kind: io.l5d.rewrite
      prefix: /portNsSvcToK8s
      pattern: "/{port}/{ns}/{svc}"
      name: "/k8s/{ns}/{port}/{svc}"
    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25
    usage:
      enabled: false
    routers:
    - protocol: http
      label: outgoing
      dtab: |
        /k8s          =>   /#/io.l5d.k8s.out;
        /portNsSvc    =>   /#/portNsSvcToK8s;
        /host         =>   /portNsSvc/http/default;
        /host         =>   /portNsSvc/http;
        /svc          =>   /$/io.buoyant.http.domainToPathPfx/host;
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX
    - protocol: http
      label: incoming
      dtab: |
        /k8s          =>   /#/io.l5d.k8s.in;
        /portNsSvc    =>   /#/portNsSvcToK8s;
        /host         =>   /portNsSvc/http/default;
        /host         =>   /portNsSvc/http;
        /svc          =>   /$/io.buoyant.http.domainToPathPfx/host;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
          hostNetwork: true
      servers:
      - port: 4141
        ip: 0.0.0.0
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  selector:
    matchLabels:
      app: l5d
  template:
    metadata:
      labels:
        app: l5d
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        image: buoyantio/linkerd:1.3.6
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: incoming
          containerPort: 4141
          hostPort: 4141
        - name: admin
          containerPort: 9990
          hostPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"

      - name: kubectl
        image: zhanyang/kubectl:1.9.3
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
spec:
  selector:
    app: l5d
  clusterIP: None
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990